### ISSUE TITLE
Add-FormatTableView.ps1: probably some bugs

### ISSUE THREAD

**Issue by schittli** [DBremen/PowerShellScripts#2]
Hello
I tried to use Add-FormatTableView.ps1 and got problems in this code:
```
$xmlPath = Join-Path (Split-Path $profile.CurrentUserCurrentHost)  ($ViewName + '.format.ps1xml')
    Get-FormatData -TypeName $TypeNames | Export-FormatData -Path $xmlPath
    Update-FormatData -PrependPath $xmlPath
$xmlPath

```

1. If $profile.CurrentUserCurrentHost is empty, does the script works as expected?

2. Does the script really needs to return $xmlPath on the last line?

And this one:
```
[Parameter(Position=3)] 
[Management.Automation.Alignment] $Alignment = 'Undefined',
```
Shouldn't the Alignement parameter be an array?

Kind regards, Tom

**Comment by DBremen** [comment]
Hi, Tom. Better late than never ;-). Thanks a lot. I've fixed the bugs, based on your feedback. I have the script returning the path to the format file in order to use it with Update-FormatData (see example 1). Thanks, Dirk.

**Comment by schittli** [comment]
Good evening DBremen, 
thanks a lot for fixing and sharing your code!, 
now I'll start over and think about my initial motivation to use your tools :-)

Kind regards and all the best, Tom
